- name: Install key for Cloudera repository
  rpm_key:  state=present key=https://archive.cloudera.com/cdh5/redhat/7/x86_64/cdh/RPM-GPG-KEY-cloudera
  when: ansible_os_family == 'RedHat'

- name: Install Cloudera Manager repo
  yum_repository: baseurl=https://archive.cloudera.com/cm5/redhat/7/x86_64/cm/5/ state=present gpgcheck=1 name=ClouderaManager description="Repository to provide Cloudera Manager packages"

- name: Install necessary packages
  yum: name={{ item }} update_cache=yes state=present
  with_items:
    - cloudera-manager-daemons
    - cloudera-manager-agent

- name: Create cloudera agent config
  template:
    src: config.ini.j2
    dest: /etc/cloudera-scm-agent/config.ini
    owner:
    group:

- name: Start Cloudera Agent
  service:
    name: cloudera-scm-agent
    state: started
    enabled: yes

- name: Create Hive lib dir
  file:
    state: directory
    recurse: yes
    path: /opt/local/hive/lib
    mode: 0777