- name: Ensure Cloudera Manager repo exists
  get_url:
    url: "{{ CM_REPO_URL }}"
    dest: /etc/yum.repos.d/cm.repo

- name: Ensure Cloudera Manager Agent is installed
  yum:
    name: cloudera-manager-agent
    state: present

- name: Ensure Cloudera Manager Agent configuration is up-to-date
  template:
    src: config.ini.j2
    dest: /etc/cloudera-scm-agent/config.ini
  notify: restart cloudera manager agent

- name: Ensure JDK is installed
  yum:
    name: "{{ CM_JDK_PACKAGE }}"
    state: present
  when: CM_INSTALL_JDK

- name: Ensure Cloudera Manager Agent is started
  service:
    name: cloudera-scm-agent
    state: started
    enabled: yes
